// Stranger Thinking — strategy deck
// Edit this list freely; the page picks one at random on each draw.

export const strategies: readonly string[] = [
  "Honor thy error as a hidden intention",
  "Use an old idea",
  "Make the problem the solution",
  "Only one element of each kind",
  "Maximize it",
  "Minimize it",
  "What to increase? What to reduce?",
  "Try faking it",
  "Work at a different speed",
  "Abandon normal instruments",
  "Treat it like a commandment",
  "A line has two sides",
  "Abandon structure",
  "Articulate your suspicions",
  "Be extravagant",
  "Assume the critic's mindset",
  "Betray your audience",
  "Change instruments",
  "Assume the mind of a child",
  "Cut a vital connection",
  "Define an area as 'safe' and use it as an anchor",
  "Destroy the most important thing",
  "Discard an axiom",
  "Time travel. 100 years back. 1000 years forward",
  "It's Day One",
  "Write down the recipes you are using. Avoid them.",
  "Distorting time",
  "Do nothing for as long as possible",
  "Don't be frightened of clichés",
  "Choose one word.",
  "Choose Imperfection.",
  "Define perfection.",
  "Do we need holes?",
  "Jump categories.",
  "Call out the category clichés",
  "Emphasize differences",
  "Emphasize repetitions",
  "Emphasize the flaws",
  "Faced with a choice, do both",
  "Fill every beat with something",
  "Give the game away",
  "Give way to your worst impulse",
  "Go slowly all the way round the outside",
  "Humanize something free of error",
  "Visualize the impossible",
  "What if it's actually finished?",
  "Wrong answers only.",
  "Left of, right of, dead center",
  "Amplify the quiet voice",
  "Look at the order in which you do things",
  "Look closely at the most embarrassing details and amplify them",
  "Lost in usable material",
  "Modernize the archive",
  "Prepare the eulogy",
  "Find the lowest common denominator",
  "Choose an exquisite frame",
  "Make an exhaustive list of everything you might do and do the last thing on the list",
  "Make a sudden, destructive unpredictable action — incorporate",
  "The most important thing is the thing most easily forgotten",
  "Move towards the unimportant",
  "Not building a wall but making a brick",
  "Overstated",
  "Unlaunch",
  "Remove specifics and convert to ambiguities",
  "Remove the middle, extend the edges",
  "Repetition is a form of change",
  "Reverse the order",
  "Fill it with Pink Air.",
  "Make a point to be self-effacing & deferential with your invitation.",
  "Take your enemy's point of view",
  "Simple subtraction",
  "Spectrum analysis",
  "Take a break",
  "Take away the elements in order of apparent non-importance",
  "Make inconsistency the rule",
  "Turn it upside down",
  "Break the guidelines",
  "Voice your suspicions",
  "Righteous anger",
  "Lie, obviously.",
  "Dadaism. Reject convention & reason. Embrace absurdity & nonsense.",
  "Say the unspoken thing.",
  "What are you really thinking about just now?",
  "What is the reality of your make-believe?",
  "What mistakes did you make last time?",
  "What if you skipped a step?",
  "What would make this easier to do?",
  "When is it for? Who is it for?",
  "Why did it go extinct?",
  "Browse the book store. Pick a random book, and copy the first line.",
  "Where is the edge? Where does the edge become the important part?",
  "Create a new life stage",
  "Pick a moment you can win.",
  "Seek advice in unexpected places.",
  "Work like a child. Think like a teenager. Play like an adult.",
  "Make it a beer/perfume/car/pharmaceutical.",
  "Give your protestors something to talk about.",
  "Give the Pope something to talk about.",
  "Don't use words.",
  "Use an unconventional medium.",
  "Squash a revolution.",
  "Start inside the building.",
  "Make fun of your audience.",
  "Celebrate your critics.",
  "Go dangerously fast.",
  "Safe transgression.",
  "No shame.",
  "Turn the lights off.",
  "Frame your enemy as mediocre",
  "Distract from the issue at hand by any means possible.",
  "Changing your mind is a sign of intelligence.",
  "Loyalists are under appreciated.",
  "Love a forgotten thing and make a show of it.",
  "Change the music and see what happens.",
  "Write so slow it hurts.",
  "You don't have to be ashamed of using your own ideas",
] as const;
